spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking-app
    username: postgres
    password: anas5313N
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
